### ISSUE TITLE
See the attached image :))

### ISSUE THREAD

**Issue by glorand** [iboyperson/ulauncher-system#10]
![Screenshot from 2020-12-15 09-44-22](https://user-images.githubusercontent.com/883989/102185781-41942880-3eba-11eb-98e1-947e73c0e98c.png)

**Comment by tjquillan** [comment]
Hi, thanks for reporting this. Can you show me the logs so I can better diagnose the problem? The easiest way I know of getting this is simply launching ulauncher in the command line and giving me its output.

**Comment by tjquillan** [comment]
Hi, I just pushed a commit ac5ed78 that might fix your problem if my hunch is correct. Please let me know if this persists.

**Comment by feimosi** [comment]
@iboyperson I'm having the same issue, here are the logs:
```
2021-04-13 09:15:35,246 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.iboyperson.ulauncher-system" exited instantly with code 1
2021-04-13 09:15:35,246 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.iboyperson.ulauncher-system" failed with an error: ImportError: Requiring namespace 'Gdk' version '3.0', but '4.0' is already loaded
```

Started happening after upgrading to Gnome 40, which uses Gdk 4.0 now.

**Comment by tjquillan** [comment]
Hi, @feimosi I believe your issue is different than @glorand had. If its not too much to ask can you create a separate issue for tracking your problem as it is one I can try to fix.

Edit: I already created an issue to track it: https://github.com/iboyperson/ulauncher-system/issues/14. I am closing this one as it is far to vague to be helpful (and as seen in https://github.com/iboyperson/ulauncher-system/issues/10#issuecomment-770253628 it may already be fixed)

**Comment by feimosi** [comment]
No problem, thanks for the quick reply!
