### ISSUE TITLE
how to solve this error, I use ubuntu 19.04 ?

### ISSUE THREAD

**Issue by putu-eka-mulyana** [iboyperson/ulauncher-system#7]
![image](https://user-images.githubusercontent.com/28705956/72681596-16655580-3b00-11ea-9336-265eedf0fb83.png)

**Comment by tjquillan** [comment]
This extension is only compatible with Ulauncher API v2.0.0. In order to use this extension you will need to Update to Ulauncher 5. 

This page: https://ulauncher.io/#Download contains a link to a PPA for Ubuntu (or the direct deb file if you prefer) for Ulauncher 5

Edit: Here is some info on Ubuntu PPAs just in case: https://vitux.com/how-to-add-remove-ppa-repositories-in-ubuntu/
